# -*- coding: utf-8 -*-
"""heroku.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgllAjLumvo0jgaFyFvTzCAQglmkHmyz
"""

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
import pickle

st.write("""
# Get Largest 3 number
""")
#Get Input

st.header('User Input Parameters')

def user_input_features():
   
    number1 = st.number_input("number 1",min_value=0,max_value=200000,step=1)
    number2 = st.number_input("number 2",min_value=0,max_value=200000,step=1)
    number3 = st.number_input("number 3",min_value=0,max_value=20000,step=1)

    return number1, number2, number3

number1, number2, number3 = user_input_features()
maxnum = max(number1, max(number2, number3))

st.subheader('Largest')
st.write(maxnum)